/* Maki adapter — append-only session JSONL under the Maki state directory. */
import { readdir, readFile, stat } from 'fs/promises';
import { basename, join } from 'path';
import { homedir } from 'os';
import type { Adapter, AdapterInfo, CanonPart, Conversation, Message, ParseOptions, ToolCall } from '../types/index.ts';
import { isUnderAnyCanonicalRoot, runAdapter, textPart, thinkingPart, toolCallPart, toolResultPart } from '../types/index.ts';
const ROOTS=[join(process.env.XDG_STATE_HOME??join(homedir(),'.local','state'),'maki','sessions'),join(homedir(),'.maki','sessions')];
type J=Record<string,any>;
const adapter:Adapter={info():AdapterInfo{return{name:'maki',displayName:'Maki',version:'1.0.0',defaultPaths:ROOTS}},async detect(path){if(!isUnderAnyCanonicalRoot(path,ROOTS))return null;return(await files(path)).length?0.9:null},async parse(path,opts){const out:Conversation[]=[];for(const file of await files(path)){const c=await parseFile(file,opts);if(c)out.push(c)}out.sort((a,b)=>b.createdAt-a.createdAt);return opts?.limit?out.slice(0,opts.limit):out}};
async function files(path:string):Promise<string[]>{try{const s=await stat(path);if(s.isFile()&&path.endsWith('.jsonl'))return[path]}catch{return[]}const out:string[]=[];try{for(const e of await readdir(path,{withFileTypes:true}))if(e.isFile()&&e.name.endsWith('.jsonl')&&!['cwd_latest.jsonl','scan_cache.jsonl'].includes(e.name))out.push(join(path,e.name))}catch{}return out}
async function parseFile(file:string,opts?:ParseOptions):Promise<Conversation|null>{let raw='';try{raw=await readFile(file,'utf8')}catch{return null}let id=basename(file,'.jsonl'),model:string|undefined,workspace:string|undefined,title:string|undefined,createdAt=0,updatedAt=0,tokensIn=0,tokensOut=0,costUsd=0;const messages:Message[]=[];for(const line of raw.split(/\r?\n/)){if(!line.trim())continue;let r:J;try{r=JSON.parse(line)}catch{continue}if(r.t==='header'){id=String(r.id??id);model=str(r.model);workspace=str(r.cwd);createdAt=num(r.created_at)??createdAt}else if(r.t==='meta'){title=str(r.title)??title;updatedAt=num(r.updated_at)??updatedAt;for(const u of Object.values(r.usage_by_model??{}) as J[]){tokensIn+=(num(u.input)??0)+(num(u.cache_read)??0)+(num(u.cache_creation)??0);tokensOut+=num(u.output)??0;costUsd+=num(u.cost)??0}}else if(r.t==='msg'&&r.d?.kind!=='observation'){const m=message(r.d,opts);if(m)messages.push(m)}else if(r.t==='out'&&opts?.includeTools!==false){const output=typeof r.d==='string'?r.d:JSON.stringify(r.d??'');messages.push({role:'tool',content:output,parts:[toolResultPart(String(r.id??'unknown'),output)]})}}
if(!messages.length)return null;updatedAt=updatedAt||createdAt;if(opts?.since&&updatedAt<opts.since)return null;return{externalId:id,title:title??messages.find(m=>m.role==='user')?.content.slice(0,100)??'(untitled)',createdAt:createdAt||updatedAt||Date.now(),updatedAt,model,workspace,tokensIn,tokensOut,costUsd:costUsd||undefined,messages,metadata:{source:'maki'}}}
function message(d:J,opts?:ParseOptions):Message|null{const role=d.role==='assistant'?'assistant':'user';const parts:CanonPart[]=[];const calls:ToolCall[]=[];let content='';for(const b of d.content??[]){if(b.type==='text'){content+=`${content?'\n':''}${b.text??''}`;parts.push(textPart(String(b.text??'')))}else if(b.type==='thinking')parts.push(thinkingPart(String(b.thinking??'')));else if(b.type==='tool_use'){calls.push({toolName:String(b.name??'tool'),input:b.input,status:'pending'});parts.push(toolCallPart(String(b.id??'unknown'),String(b.name??'tool'),b.input))}else if(b.type==='tool_result'&&opts?.includeTools!==false)parts.push(toolResultPart(String(b.tool_use_id??'unknown'),b.content,{isError:Boolean(b.is_error)}))}if(!content&&!parts.length)return null;return{role,content:d.display_text??content,parts,toolCalls:calls.length?calls:undefined}}
function str(v:unknown){return typeof v==='string'?v:undefined}function num(v:unknown){return typeof v==='number'&&Number.isFinite(v)?Math.floor(v):undefined}
runAdapter(adapter);
